<#
.SYNOPSIS
    Builds, packages and publishes a Schedule I Expansions release.

.DESCRIPTION
    Releases are cut from the owner's machine, not from CI. The mod projects
    reference the Il2Cpp interop assemblies that MelonLoader generates from the
    installed copy of Schedule I; those assemblies cannot legally or practically
    live in the repository, so a GitHub-hosted runner cannot compile this suite.
    See docs/RELEASING.md for the full reasoning.

    This script:
      1. refuses to run against a dirty tree or an existing tag,
      2. builds src/Expansions.sln (and CreativeMode.csproj as a compile check),
      3. stages the distributable tree, verifying every payload file exists and
         is non-empty,
      4. writes the zip and re-opens it to confirm the layout,
      5. writes update-manifest.json (schema in docs/UPDATE-MANIFEST.md),
      6. tags, pushes, and creates the GitHub Release with both assets.

    Creative Mode is deliberately never packaged.

.EXAMPLE
    .\scripts\publish.ps1 -Version 1.2.2 -Changelog "Fixes the drivers clipboard." -DryRun

.EXAMPLE
    .\scripts\publish.ps1 -Version 1.2.2 -Changelog "Fixes the drivers clipboard."
#>
[CmdletBinding()]
param(
    # Suite version, SemVer, no leading "v". The git tag becomes "v<Version>".
    [Parameter(Mandatory = $true)]
    [ValidatePattern('^\d+\.\d+\.\d+(-[0-9A-Za-z.\-]+)?$')]
    [string] $Version,

    # One-line summary the in-game updater shows the player. Keep it short.
    [string] $Changelog = '',

    # Optional path to a markdown file used as the GitHub Release body.
    [string] $NotesFile = '',

    # Build and package, but do not tag, push or create the release.
    [switch] $DryRun,

    # Reuse whatever is already in bin/Release instead of rebuilding.
    [switch] $SkipBuild,

    # Skip the CreativeMode.csproj compile check (it redeploys the owner's
    # local Mods\CreativeMode.dll as a side effect of building).
    [switch] $SkipCreativeMode,

    # Publish the GitHub Release as a draft.
    [switch] $Draft,

    # Mark the GitHub Release as a prerelease.
    [switch] $PreRelease,

    # Package even though the working tree has uncommitted changes.
    [switch] $AllowDirty,

    # Overwrite an existing tag / release of the same version.
    [switch] $Force,

    [string] $GameDir = 'C:\Program Files (x86)\Steam\steamapps\common\Schedule I'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------

function Write-Step { param([string] $Message) Write-Host "==> $Message" -ForegroundColor Cyan }
function Write-Ok   { param([string] $Message) Write-Host "    $Message" -ForegroundColor DarkGray }
function Fail       { param([string] $Message) throw $Message }

function Get-Sha256 {
    param([string] $Path)
    (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()
}

function Resolve-Gh {
    $onPath = Get-Command gh -ErrorAction SilentlyContinue
    if ($onPath) { return $onPath.Source }
    $fallback = 'C:\Program Files\GitHub CLI\gh.exe'
    if (Test-Path -LiteralPath $fallback) { return $fallback }
    Fail 'GitHub CLI not found. Install it or add gh to PATH.'
}

function Invoke-Checked {
    param([string] $Exe, [string[]] $Arguments, [string] $What)
    & $Exe @Arguments
    if ($LASTEXITCODE -ne 0) { Fail "$What failed (exit $LASTEXITCODE): $Exe $($Arguments -join ' ')" }
}

$RepoRoot = Split-Path -Parent $PSScriptRoot
Push-Location $RepoRoot
try {

# --------------------------------------------------------------------------
# 0. Preconditions
# --------------------------------------------------------------------------

Write-Step "Publishing Schedule I Expansions v$Version"

$Tag = "v$Version"
$gh  = Resolve-Gh

if (-not (Test-Path -LiteralPath (Join-Path $GameDir 'MelonLoader\Il2CppAssemblies'))) {
    Fail @"
Il2Cpp interop assemblies not found under:
  $GameDir\MelonLoader\Il2CppAssemblies

The suite cannot be compiled without them. They are generated by MelonLoader
from the installed game, which is why releases are built locally and never in
CI. Launch the game once with MelonLoader installed, then retry.
"@
}

if (-not $AllowDirty) {
    $dirty = git status --porcelain=v1
    if ($dirty) {
        Fail @"
Working tree is dirty. A release tag must point at committed code.
Commit or stash first, or pass -AllowDirty if you know what you are doing.

$($dirty -join [Environment]::NewLine)
"@
    }
}

$existingTag = git tag --list $Tag
if ($existingTag -and -not $Force) {
    Fail "Tag $Tag already exists. Bump -Version, or pass -Force to replace it."
}

# --------------------------------------------------------------------------
# 1. Build
# --------------------------------------------------------------------------

if ($SkipBuild) {
    Write-Step 'Skipping build (-SkipBuild); using existing bin\Release output'
} else {
    Write-Step 'Building src\Expansions.sln (Release)'
    Invoke-Checked 'dotnet' @('build', 'src\Expansions.sln', '-c', 'Release', '--nologo', '-v', 'minimal') 'Expansions build'

    if ($SkipCreativeMode) {
        Write-Ok 'Skipped CreativeMode.csproj compile check (-SkipCreativeMode)'
    } else {
        Write-Step 'Compile-checking CreativeMode.csproj (Release) - not packaged'
        Write-Ok 'Note: building this refreshes your local Mods\CreativeMode.dll.'
        Invoke-Checked 'dotnet' @('build', 'CreativeMode.csproj', '-c', 'Release', '--nologo', '-v', 'minimal') 'CreativeMode build'
    }
}

# --------------------------------------------------------------------------
# 2. Payload definition
# --------------------------------------------------------------------------

# installDir is relative to the Schedule I game root. "" means the game root.
$mods = @(
    [ordered]@{ id = 'expansions_core';   name = 'Expansions Core';    installDir = 'UserLibs'; source = 'src\Expansions.Core\bin\Release\Expansions.Core.dll' }
    [ordered]@{ id = 'hireable_drivers';  name = 'Hireable Drivers';   installDir = 'Mods';     source = 'src\Expansions.HireableDrivers\bin\Release\Expansions.HireableDrivers.dll' }
    [ordered]@{ id = 'police_overhaul';   name = 'Police Improvements'; installDir = 'Mods';    source = 'src\Expansions.PoliceOverhaul\bin\Release\Expansions.PoliceOverhaul.dll' }
    [ordered]@{ id = 'special_customers'; name = 'Special Customers';  installDir = 'Mods';     source = 'src\Expansions.SpecialCustomers\bin\Release\Expansions.SpecialCustomers.dll' }
)

# Redistributed unmodified under MIT; LICENSE-S1API.txt carries the notice.
$dependencies = @(
    [ordered]@{ id = 's1api';        name = 'S1API (Forked, IL2CPP)'; installDir = 'Mods';    source = (Join-Path $GameDir 'Mods\S1API.Il2Cpp.MelonLoader.dll') }
    [ordered]@{ id = 's1api_loader'; name = 'S1API Loader';           installDir = 'Plugins'; source = (Join-Path $GameDir 'Plugins\S1APILoader.MelonLoader.dll') }
)

$documents = @(
    [ordered]@{ name = 'Install runbook';        installDir = ''; source = 'INSTALL.txt' }
    [ordered]@{ name = 'Feature reference';      installDir = ''; source = 'FEATURES.txt' }
    [ordered]@{ name = 'Third-party notice';     installDir = ''; source = 'packaging\LICENSE-S1API.txt' }
)

foreach ($item in @($mods) + @($dependencies) + @($documents)) {
    if (-not (Test-Path -LiteralPath $item.source -PathType Leaf)) {
        Fail "Payload file missing: $($item.source)"
    }
    if ((Get-Item -LiteralPath $item.source).Length -eq 0) {
        Fail "Payload file is empty: $($item.source)"
    }
    $item.fileName = Split-Path -Leaf $item.source
    $item.entry    = if ($item.installDir) { "$($item.installDir)/$($item.fileName)" } else { $item.fileName }
}

# Per-mod versions come from the compiled assembly, so the manifest can never
# disagree with what actually shipped.
foreach ($mod in $mods) {
    $full = (Resolve-Path -LiteralPath $mod.source).Path
    $info = [System.Diagnostics.FileVersionInfo]::GetVersionInfo($full)
    $mod.version = if ($info.ProductVersion) { $info.ProductVersion.Trim() } else { $info.FileVersion.Trim() }
    if (-not $mod.version) { Fail "Could not read a version from $($mod.fileName)" }
}

# --------------------------------------------------------------------------
# 3. Package
# --------------------------------------------------------------------------

$distDir      = Join-Path $RepoRoot 'dist'
$zipName      = "ScheduleI-Expansions-$Version.zip"
$zipPath      = Join-Path $distDir $zipName
$manifestPath = Join-Path $distDir 'update-manifest.json'

Write-Step "Packaging $zipName"

New-Item -ItemType Directory -Force -Path $distDir | Out-Null
# CONTEXT.md: only ever keep one archive in dist/.
Get-ChildItem -LiteralPath $distDir -Filter 'ScheduleI-Expansions-*.zip' -File -ErrorAction SilentlyContinue |
    ForEach-Object { Write-Ok "removing stale archive $($_.Name)"; Remove-Item -LiteralPath $_.FullName -Force }
if (Test-Path -LiteralPath $zipPath) { Remove-Item -LiteralPath $zipPath -Force }

Add-Type -AssemblyName System.IO.Compression
Add-Type -AssemblyName System.IO.Compression.FileSystem

# Written entry-by-entry rather than CreateFromDirectory so the archive layout
# is explicit and always uses forward slashes.
$ordered = @($documents) + @($mods | Where-Object { $_.installDir -eq 'Mods' }) +
           @($dependencies | Where-Object { $_.installDir -eq 'Mods' }) +
           @($dependencies | Where-Object { $_.installDir -eq 'Plugins' }) +
           @($mods | Where-Object { $_.installDir -eq 'UserLibs' })

$archive = [System.IO.Compression.ZipFile]::Open($zipPath, [System.IO.Compression.ZipArchiveMode]::Create)
try {
    foreach ($item in $ordered) {
        $full  = (Resolve-Path -LiteralPath $item.source).Path
        $entry = $archive.CreateEntry($item.entry, [System.IO.Compression.CompressionLevel]::Optimal)
        $entry.LastWriteTime = (Get-Item -LiteralPath $full).LastWriteTime
        $out = $entry.Open()
        try { $bytes = [System.IO.File]::ReadAllBytes($full); $out.Write($bytes, 0, $bytes.Length) }
        finally { $out.Dispose() }
        Write-Ok $item.entry
    }
} finally { $archive.Dispose() }

# Re-open and verify, so an empty or truncated release is impossible.
$verify = [System.IO.Compression.ZipFile]::OpenRead($zipPath)
try {
    $actual   = $verify.Entries | ForEach-Object { $_.FullName }
    $expected = $ordered | ForEach-Object { $_.entry }
    $missing  = $expected | Where-Object { $actual -notcontains $_ }
    if ($missing) { Fail "Archive is missing entries: $($missing -join ', ')" }
    if ($actual.Count -ne $expected.Count) { Fail "Archive has $($actual.Count) entries, expected $($expected.Count)." }
    foreach ($e in $verify.Entries) {
        if ($e.Length -eq 0) { Fail "Archive entry is empty: $($e.FullName)" }
    }
} finally { $verify.Dispose() }

Write-Ok ("{0} entries, {1:N0} bytes" -f $ordered.Count, (Get-Item -LiteralPath $zipPath).Length)

# --------------------------------------------------------------------------
# 4. Manifest
# --------------------------------------------------------------------------

Write-Step 'Writing update-manifest.json'

$originUrl = (git remote get-url origin 2>$null)
if (-not $originUrl) { Fail 'No git remote "origin". Add one before publishing.' }
if ($originUrl -notmatch 'github\.com[:/](?<owner>[^/]+)/(?<repo>[^/.]+)') {
    Fail "Could not parse a GitHub owner/repo out of origin: $originUrl"
}
$owner    = $Matches['owner']
$repoName = $Matches['repo']
$slug     = "$owner/$repoName"

$downloadBase = "https://github.com/$slug/releases/download/$Tag"

function New-FileEntry {
    param($Item, [switch] $IncludeVersion, [switch] $ThirdParty)
    $full = (Resolve-Path -LiteralPath $Item.source).Path
    $e = [ordered]@{ id = $null; name = $Item.name }
    if ($Item.Contains('id')) { $e.id = $Item.id } else { $e.Remove('id') }
    if ($IncludeVersion) { $e.version = $Item.version }
    $e.fileName   = $Item.fileName
    $e.installDir = $Item.installDir
    $e.sizeBytes  = [int64](Get-Item -LiteralPath $full).Length
    $e.sha256     = Get-Sha256 $full
    if ($ThirdParty) { $e.thirdParty = $true; $e.overwriteExisting = $false }
    return $e
}

$manifest = [ordered]@{
    schemaVersion = 1
    suite         = 'ScheduleI-Expansions'
    version       = $Version
    tag           = $Tag
    releasedAt    = [DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ssZ')
    changelog     = $Changelog
    releaseNotesUrl = "https://github.com/$slug/releases/tag/$Tag"
    requires      = [ordered]@{
        melonLoaderMinimum = '0.7.3'
        gameVersionTested  = '0.4.6f11'
    }
    package       = [ordered]@{
        fileName  = $zipName
        url       = "$downloadBase/$zipName"
        sizeBytes = [int64](Get-Item -LiteralPath $zipPath).Length
        sha256    = (Get-Sha256 $zipPath)
    }
    mods                 = [object[]]@($mods         | ForEach-Object { New-FileEntry $_ -IncludeVersion })
    bundledDependencies  = [object[]]@($dependencies | ForEach-Object { New-FileEntry $_ -ThirdParty })
    documents            = [object[]]@($documents    | ForEach-Object { New-FileEntry $_ })
}

$json = $manifest | ConvertTo-Json -Depth 8
[System.IO.File]::WriteAllText($manifestPath, $json, (New-Object System.Text.UTF8Encoding($false)))
Write-Ok "$manifestPath"
Write-Ok "package sha256 $($manifest.package.sha256)"
foreach ($m in $manifest.mods) { Write-Ok ("{0,-20} {1}" -f $m.id, $m.version) }

if ($DryRun) {
    Write-Step 'Dry run: stopping before tag / push / release'
    Write-Host ''
    Write-Host "  zip      $zipPath"
    Write-Host "  manifest $manifestPath"
    Write-Host ''
    return
}

# --------------------------------------------------------------------------
# 5. Tag, push, release
# --------------------------------------------------------------------------

Write-Step "Tagging $Tag"
if ($existingTag -and $Force) {
    Invoke-Checked 'git' @('tag', '-d', $Tag) 'delete local tag'
    git push origin ":refs/tags/$Tag" 2>$null | Out-Null
}
$tagMessage = if ($Changelog) { "$Tag - $Changelog" } else { $Tag }
Invoke-Checked 'git' @('tag', '-a', $Tag, '-m', $tagMessage) 'git tag'
Invoke-Checked 'git' @('push', 'origin', $Tag) 'git push tag'

Write-Step "Creating GitHub Release $Tag on $slug"

if ($Force) {
    & $gh release delete $Tag --repo $slug --yes --cleanup-tag=false 2>$null | Out-Null
}

$notes = if ($NotesFile) {
    if (-not (Test-Path -LiteralPath $NotesFile)) { Fail "Notes file not found: $NotesFile" }
    Get-Content -LiteralPath $NotesFile -Raw
} else {
@"
$Changelog

## Install

Unzip into your Schedule I folder, merging ``Mods``, ``Plugins`` and ``UserLibs``.
Full runbook: ``INSTALL.txt`` inside the zip.

Requires MelonLoader $($manifest.requires.melonLoaderMinimum) or newer.
Built and tested against game version $($manifest.requires.gameVersionTested).

## Contents

| Mod | Version |
|-----|---------|
$(( $manifest.mods | ForEach-Object { "| $($_.name) | $($_.version) |" } ) -join [Environment]::NewLine)

``$zipName`` SHA-256: ``$($manifest.package.sha256)``

``update-manifest.json`` is consumed by the in-game auto-updater. Schema:
[docs/UPDATE-MANIFEST.md](https://github.com/$slug/blob/main/docs/UPDATE-MANIFEST.md).
"@
}

$notesPath = Join-Path $distDir 'release-notes.md'
[System.IO.File]::WriteAllText($notesPath, $notes, (New-Object System.Text.UTF8Encoding($false)))

$ghArgs = @('release', 'create', $Tag,
            '--repo', $slug,
            '--title', "Schedule I Expansions $Version",
            '--notes-file', $notesPath,
            $zipPath, $manifestPath)
if ($Draft)      { $ghArgs += '--draft' }
if ($PreRelease) { $ghArgs += '--prerelease' }

Invoke-Checked $gh $ghArgs 'gh release create'

Write-Step 'Published'
Write-Host ''
Write-Host "  https://github.com/$slug/releases/tag/$Tag"
Write-Host ''
Write-Host '  The updater reads the manifest from this stable URL:'
Write-Host "  https://github.com/$slug/releases/latest/download/update-manifest.json"
Write-Host ''

} finally { Pop-Location }
